"""Per-run randomisation, generated by the SCORER.

The app receives values; the scorer keeps the meaning. The app never learns
which strings matter or who owns them, so an RCE cannot enumerate the
planted-secret map — only the secrets themselves, which the DB held anyway.

Randomising the VALUE while preserving the PROPERTY is the whole game. The JWT
secret must stay dictionary-crackable or `jwt-weak-secret` becomes unsolvable,
so it is drawn from a wordlist rather than from urandom.
"""
import base64, os, random, secrets, time

# Present in rockyou; cracking one with hashcat is the intended solve path.
WORDLIST = ["bubbles", "sparkle", "seltzer", "sunshine", "dragon", "monkey",
            "letmein", "princess", "football", "shadow", "master", "flower",
            "summer", "orange", "purple", "silver", "thunder", "cookie"]


def _run_id():
    return time.strftime("%Y%m%dT%H%M%SZ", time.gmtime()) + "-" + secrets.token_hex(3)


def generate(rng=None):
    rng = rng or random.SystemRandom()
    run = _run_id()
    prefix = f"SPRKL-{secrets.token_hex(2).upper()}-"
    C = lambda label: prefix + label

    tokens, spec = {}, {"token_prefix": prefix}

    def plant(label, owner, kind):
        tok = C(label)
        tokens[tok] = {"owner": owner, "kind": kind}
        return tok

    users = []
    for uid, email, pw, name, role, org, addr, loy in [
            (1, "alice@example.com", "password1", "Alice Retail", "customer", None, "12 Fizz Lane", 120),
            (2, "bob@example.com", "hunter2", "Bob Bubbles", "customer", None, "9 Seltzer St", 40),
            (3, "carol@sprkl-corp.com", "Summer2026!", "Carol Corp", "buyer", 100, "1 Corporate Way", 0),
            (4, "dave@rival-corp.com", "Rival2026!", "Dave Rival", "buyer", 200, "5 Rival Rd", 0),
            (5, "admin@sprkl-corp.com", "admin", "SPRKL Admin", "admin", 100, "HQ", 0)]:
        users.append({"id": uid, "email": email, "password": pw, "name": name,
                      "role": role, "org_id": org, "address": addr, "loyalty": loy,
                      "secret": plant(f"USER-{uid}", f"user:{uid}", "user-secret")})
    spec["users"] = users

    products = []
    for i, (slug, name, flavor, price) in enumerate([
            ("classic", "SPRKL Classic", "Original", 3.50),
            ("lime", "SPRKL Lime Twist", "Lime", 3.75),
            ("berry", "SPRKL Wild Berry", "Berry", 3.95),
            ("grapefruit", "SPRKL Grapefruit", "Grapefruit", 3.75),
            ("cola", "SPRKL Cola Fizz", "Cola", 4.25)], 1):
        products.append({"id": i, "slug": slug, "name": name, "flavor": flavor,
                         "price": price, "listed": 1,
                         "secret": plant(f"PROD-{i}", "system", "product-secret")})
    products.append({"id": 99, "slug": "proto-x", "name": "SPRKL Prototype X",
                     "flavor": "Secret", "price": 9.99, "listed": 0,
                     "secret": plant("PROD-UNLISTED", "system", "product-secret")})
    spec["products"] = products

    spec["orders"] = [
        {"id": oid, "user_id": uid, "total": tot, "status": st, "ref": ref,
         "secret": plant(f"ORDER-{oid}", f"user:{uid}", "order-secret")}
        for oid, uid, tot, st, ref in [
            (1001, 1, 42.0, "delivered", "SP-AAA111"),
            (1002, 2, 18.5, "shipped", "SP-BBB222"),
            (1003, 3, 980.0, "processing", "SP-CCC333"),
            (1004, 4, 1200.0, "processing", "SP-DDD444")]]

    spec["giftcards"] = [
        {"id": 1, "owner_id": 1, "code": "GC-ALICE-1", "balance": 50.0,
         "secret": plant("GC-1", "user:1", "giftcard-secret")},
        {"id": 2, "owner_id": 2, "code": "GC-BOB-2", "balance": 25.0,
         "secret": plant("GC-2", "user:2", "giftcard-secret")}]

    spec["wishlists"] = [
        {"id": 1, "user_id": 1, "item": "SPRKL Lime Twist",
         "secret": plant("WISH-1", "user:1", "wishlist-secret")},
        {"id": 2, "user_id": 2, "item": "SPRKL Cola Fizz",
         "secret": plant("WISH-2", "user:2", "wishlist-secret")}]

    spec["coupons"] = [
        {"code": "WELCOME10", "kind": "percent", "value": "10", "used": 0},
        {"code": "ONCE20", "kind": "percent", "value": "20", "used": 0},
        {"code": "FORMULA", "kind": "formula", "value": "min(50, subtotal*0.15)", "used": 0}]

    spec["nosql"] = {
        "admin_users": [
            {"username": "carol", "password": "Summer2026!", "org": 100, "role": "buyer"},
            {"username": "admin", "password": "admin", "org": 100, "role": "admin",
             "secret": plant("CORP-ADMIN", "system", "planted")}],
        "newsletter": [
            {"email": "alice@example.com", "topic": "flavors",
             "secret": plant("NL-1", "system", "planted")},
            {"email": "vip@sprkl-corp.com", "topic": "wholesale",
             "secret": plant("NL-2", "system", "planted")}]}

    spec["ldap"] = [
        {"uid": "carol", "cn": "Carol Corp", "title": "Buyer", "org": "100"},
        {"uid": "admin", "cn": "SPRKL Admin", "title": "Administrator", "org": "100",
         "secret": plant("LDAP-ADMIN", "system", "planted")}]

    spec["objstore"] = [
        {"key": "logo.png", "body": "PNG...", "private": False},
        {"key": "brochure.pdf", "body": "PDF...", "private": False},
        {"key": "private/payroll-2024.csv", "private": True,
         "body": plant("BUCKET-PAYROLL", "system", "planted")}]

    spec["assets"] = {
        "env": plant("ENV-SECRET", "system", "env"),
        "debug": plant("DEBUG-SECRET", "system", "debug"),
        "jskey": plant("JSKEY", "system", "js-key"),
        "cve": plant("CVE-2021-9999", "system", "cve"),
        "xxe_file": plant("XXE-FILE", "system", "xxe-file"),
        "iam": plant("IAM-SECRET", "system", "iam"),
        "graphql_hidden": plant("GRAPHQL-HIDDEN", "system", "planted"),
        "server_file": plant("SERVER-FILE", "system", "server-file"),
        "admin_console": plant("ADMIN-CONSOLE", "system", "planted"),
    }

    jwt_secret = rng.choice(WORDLIST)
    flask_secret = rng.choice(WORDLIST)
    mac_secret = secrets.token_bytes(rng.randint(4, 10))
    secrets_meta = {
        "jwt": {"value": jwt_secret, "source": "wordlist",
                "property": "dictionary-crackable"},
        "flask": {"value": flask_secret, "source": "wordlist",
                  "property": "dictionary-crackable"},
        "cookie_mac": {"value_len": len(mac_secret), "property": "md5-prefix-mac"},
        "coupon_aes": {"property": "cbc-padding-oracle"},
        "rng_seed": {"property": "predictable-sequence"},
    }

    app_env = {
        "SPRKL_JWT_SECRET": jwt_secret,
        "SPRKL_FLASK_SECRET": flask_secret,
        "SPRKL_COOKIE_MAC_SECRET": base64.b64encode(mac_secret).decode(),
        "SPRKL_COUPON_AES_KEY": base64.b64encode(secrets.token_bytes(16)).decode(),
        "SPRKL_WEAK_RNG_SEED": str(rng.randint(1000, 999999)),
        "SPRKL_IAM_SECRET": spec["assets"]["iam"],
    }

    manifest = {
        "run": run,
        "tokens": tokens,
        "token_prefix": prefix,
        # Passwords are in the manifest so `plaintext-password-storage` can be
        # judged proxy-side: the scorer hashes them itself and looks for the
        # digest in a response, with no help from the app.
        "accounts": [{"principal": f"user:{u['id']}", "email": u["email"],
                      "role": u["role"], "password": u["password"],
                      "default_credential": u["password"] in ("admin", "password")}
                     for u in users],
        "secrets": secrets_meta,
        "internal_cidrs": ["127.0.0.0/8", "169.254.0.0/16", "10.0.0.0/8",
                           "172.16.0.0/12", "192.168.0.0/16"],
    }
    # The app reads everything it needs from one spec file, so compose carries no
    # per-run secrets and the values differ on every boot.
    spec["env"] = app_env
    return {"run": run, "spec": spec, "manifest": manifest}
